# Generated by Django 4.1.2 on 2022-11-01 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RuServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('info', models.TextField()),
                ('img', models.ImageField(upload_to='images/')),
                ('left', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='UuServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('info', models.TextField()),
                ('img', models.ImageField(upload_to='images/')),
                ('left', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Services',
        ),
    ]
