# Generated by Django 4.1.2 on 2022-11-01 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_ruservices_uuservices_delete_services'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UuServices',
            new_name='UzServices',
        ),
    ]
